image: openjdk:8-jdk

variables:
  ANDROID_TARGET_SDK: "24"
  ANDROID_BUILD_TOOLS: "24.0.0"
  ANDROID_SDK_TOOLS: "24.4.1"

cache:
  paths:
  - tmp/.gradle/wrapper
  - tmp/.gradle/caches

before_script:
  - apt-get --quiet update --yes
  - apt-get --quiet install --yes wget tar unzip lib32stdc++6 lib32z1
  - wget --quiet --output-document=android-sdk.tgz https://dl.google.com/android/android-sdk_r${ANDROID_SDK_TOOLS}-linux.tgz
  - tar --extract --gzip --file=android-sdk.tgz
  - mkdir -p tmp
  - rm -rf tmp/android-sdk-linux
  - mv android-sdk-linux tmp/
  - export ANDROID_HOME=$PWD/tmp/android-sdk-linux
  - echo y | tmp/android-sdk-linux/tools/android --silent update sdk --no-ui --all --filter android-${ANDROID_TARGET_SDK},platform-tools,build-tools-${ANDROID_BUILD_TOOLS},extra-android-m2repository
  - export GRADLE_USER_HOME=`pwd`/tmp/.gradle
  - chmod +x ./gradlew

build:
  script:
    - ./gradlew assembleDebug
  artifacts:
    paths:
    - android/build/outputs/

build_release:
  script:
    - ./gradlew assembleRelease
  artifacts:
    paths:
    - android/build/outputs/

build_desktop:
  script:
    - ./gradlew desktop:dist
  artifacts:
    paths:
    - desktop/build/libs/

test:
  script:
    - ./gradlew tests:test --info
    - apt-get --quiet install --yes licensecheck
    - ./licensecheck.sh
  artifacts:
    paths:
    - tests/build/reports/

fdroid_build:
  script:
##    - git config --global user.email "creepy@ghost.com"
##    - git config --global user.name "Creepy Ghost"
##    - git tag -a latestfrdoid -m'latest'
    - wget https://services.gradle.org/distributions/gradle-2.2-bin.zip
    - mkdir /opt/gradle
    - unzip -d /opt/gradle gradle-2.2-bin.zip
    - export PATH=$PATH:/opt/gradle/gradle-2.2/bin
    - gradle -v
    - apt-get --quiet install --yes fdroidserver
    - git clone https://gitlab.com/fdroid/fdroidserver.git
    - git clone https://gitlab.com/fdroid/fdroiddata.git -b master --single-branch
#    - git config --global user.email "creepy@ghost.com"
#    - git config --global user.name "Creepy Ghost"
#    - git tag -a latestfrdoid -m'latest'
    - git branch
    - git show-ref | grep $(git show-ref -s -- HEAD) | sed 's|.*/\(.*\)|\1|' | grep -v HEAD | sort | uniq
    - git log -n 1 --pretty=%d HEAD | egrep -o '/.*)'| egrep -o '[a-zA-Z0-9_-]*'
    - git show -s --pretty=%d HEAD | egrep -o '/.*)'| egrep -o '[a-zA-Z0-9_-]*'
    - CB=`git show -s --pretty=%d HEAD | egrep -o '/.*)'| egrep -o '[a-zA-Z0-9_-]*'`
####    - bash -c "CB=`git show -s --pretty=%d HEAD | egrep -o '/.*)' | egrep -o '[a-zA-Z0-9_-]*'` ; sed -i \"s/commit=.*/commit=$CB/g\" fdroiddata/metadata/com.gitlab.ardash.appleflinger.android.txt"
    - cd fdroiddata
##    - sed -i 's/commit=.*/commit=latestfrdoid/g' metadata/com.gitlab.ardash.appleflinger.android.txt
    - sed -i "s/commit=.*/commit=$CB/g" metadata/com.gitlab.ardash.appleflinger.android.txt
    - grep commit metadata/com.gitlab.ardash.appleflinger.android.txt
    - cp ../fdroidserver/examples/config.py ./
    - chmod 0600 config.py
    - echo 'sdk_path = "$PWD/../tmp/android-sdk-linux"' >> config.py
#    - fdroid lint com.gitlab.ardash.appleflinger.android
    - ../fdroidserver/fdroid build -v -l -t com.gitlab.ardash.appleflinger.android
    # that built the normal current master of the upstream: now go to the branch, and build again
#    - rm -rf ./build/com.gitlab.ardash.appleflinger.android
    - ls -la ../
#    - git clone ../ ./build/com.gitlab.ardash.appleflinger.android
##    - bash -c "cd ./build/com.gitlab.ardash.appleflinger.android ; git remote remove origin ; git remote add origin ../../../"
#    - sed -i 's/commit=.*/commit=latestfrdoid/g' metadata/com.gitlab.ardash.appleflinger.android.txt
    - ../fdroidserver/fdroid build -v -l -t com.gitlab.ardash.appleflinger.android &> build.log
    - cat build.log
    - bash -c "exit `grep 'BUILD FAILED' build.log | wc -l`"
